### ISSUE TITLE
Upper case / lower case inconsistency

### ISSUE THREAD

**Issue by cyBerta** [webxdc/website#11]
Almost everything is written with in lower case on https://webxdc.github.io/website/, even titles or the name Delta Chat. However the "Download" links, "Under construction", "Imprint" and "Privacy Policy" start with an upper case. I'm not a designer, but I would like to suggest to either write everything in lowercase or use the regular capitalization.

**Comment by hpk42** [comment]
this was meanwhile fixed by @r10s i guess. thanks!
