### ISSUE TITLE
Why is everything not capitalized (lowercase)?

### ISSUE THREAD

**Issue by WofWca** [webxdc/website#32]
Even "Delta Chat":

![image](https://user-images.githubusercontent.com/39462442/218140824-58170948-2d5d-420c-9888-39748a57a580.png)

Is it intentional?

**Comment by r10s** [comment]
[yip, it is intentional](https://github.com/webxdc/website/pull/7). a bit of ancient style, know it some circles :)

it was discussed controversy, but at the end, it was that :)
