### ISSUE TITLE
refactor: use `text-transform: lowercase`

### ISSUE THREAD

**Issue by WofWca** [webxdc/website#34]
We do lower-casing for style (see #32, https://github.com/webxdc/website/pull/7). It can take time to change it if we decide to. So I think writing things in normal case, and simply transforming it with CSS is simpler.
Also not sure, but it may affect screen-readers.

**Comment by rosano** [comment]
Feel free to assign to me unless you'd like to do it.

**Comment by rosano** [comment]
Oops nevermind I think you already did it in your PR.

**Comment by WofWca** [comment]
Oh, yeah, I forgot to mention this issue in the commit.
