### ISSUE TITLE
We have xstore now

### ISSUE THREAD

**Issue by WofWca** [webxdc/website#45]
But the website doesn't link to it. We have "[Search for more apps on GitHub](https://github.com/topics/webxdc)", we could also add something like "or send 'hi' to ... from Delta Chat", or maybe dedicate a section to it. Besides the blog and the [store repo](https://codeberg.org/webxdc/store) do we have other resources talking about it?
I think it still makes sense to keep the direct download links to not overly complicate things for developers, so that it's immediately clear that apps are basically just files, and the app store is an auxiliary thing.

**Comment by hpk42** [comment]
yip, so #46 is merged, we can close this here for now.
