### ISSUE TITLE
apps store on website is not updating

### ISSUE THREAD

**Issue by hpk42** [webxdc/website#54]
seems like https://webxdc.org/apps is not updating properly via xdcget

**Comment by missytake** [comment]
Is there an .xdc which received an update less than 4 months ago? editor, calendar, corkboard, checklist are all older.

Ah, TimeTracking 0.8.0 is younger than that.

I checked the apps directory which is exposed on https://apps.testrun.org, timetracking 0.8.0 is available there.

**Comment by missytake** [comment]
Ah: 

/var/www/html/webxdc.org/apps/main.js
18:const xdcget_export = "https://webxdc.org/export";

This should be `https://apps.testrun.org` imho.
