### ISSUE TITLE
WebXDC signatures

### ISSUE THREAD

**Issue by link2xt** [webxdc/website#59]
For reference, list of common pitfalls in case we implement signatures:
https://github.com/rust-lang/cargo/issues/7212#issuecomment-1717593368

In particular, hashing .zip contents instead of the file itself is tricky if you use different zip implementation on different platforms. In case of deltachat core it may be fine as the same core is used by all apps, but Cheogram may decompress zip files differently using a different .zip implementation.

**Comment by WofWca** [comment]
FYI browser extensions also do signatures. Chromium and Firefox use different formats: `.crx` and `.xpi`. AFAIK they take the contents of the folder and not a ZIP. The process is described somewhere in Mozilla docs.

**Comment by hpk42** [comment]
Recent discussions led to not pursuing webxdc signatures anymore so i am closing this issue. 
The link to cargo is a valid note but no need to keep the issue open for it.
