### ISSUE TITLE
Replacing WebXDC with a newer version

### ISSUE THREAD

**Issue by link2xt** [webxdc/website#61]
Bots using WebXDC as a frontend web interface, such as https://codeberg.org/webxdc/store and https://github.com/deltachat-bot/public-bots need a way to upgrade the frontend while keeping already sent WebXDC updates.

Current plan is to add API that will allow the WebXDC to upgrade itself by calling a JavaScript API with a blob containing new .xdc file. WebXDC app will retrieve an update from the bot as an update, e.g. as a base64-string.

Core PR adding `dc_replace_webxdc(context, msg_id, blob, n)` API: https://github.com/deltachat/deltachat-core-rust/pull/4740
Android issue about adding a JavaScript API for `dc_replace_webxdc`: https://github.com/deltachat/deltachat-android/issues/2656

Previous idea was to allow the bot to send an upgrade directly: https://github.com/deltachat/deltachat-core-rust/pull/4532
However, it was abandoned due to backwards compatibility problems. If the client does not support upgrading, this would result in the bot thinking that there is a single upgraded WebXDC instance, while the client will have two WebXDC instances, old one and upgraded one, and WebXDC updates from the bot will only be assigned to one of them.

New `dc_replace_webxdc` API would also allow the app to modify itself, this should be kept in mind wrt. security of WebXDC. Upgrading the app can modify the manifest of the app, so if the manifest is going to contain permissions or capabilities of the app (e.g. network access), the app modifying the manifest will be able to add new permissions to itself. Another problem is that by embedding updates into the .xdc, the app may be able to exfiltrate updates normally contained within the chat when it is saved to the disk or forwarded.

**Comment by hpk42** [comment]
Further discussions led to dropping the goal for now to upgrade webxdc apps in place. 
For the time being, exporting state from an app, and importing it in a new webxdc app instance, is the (manual) way to upgrade.  We can recover the issue when thoughts/work is imminent again on xdc in-place upgrades.
